export const SHOW_CATEGORIES = "SHOW_CATEGORIES";
export const SHOW_MOVIES = "SHOW_MOVIES";
export const SHOW_MOVIES_BY_ID = "SHOW_MOVIES_BY_ID";
export const SHOW_MOVIES_BY_CATEGORY = "SHOW_MOVIES_BY_CATEGORY";
export const SHOW_CITY = "SHOW_CITY";
export const SHOW_CINEMA = "SHOW_CINEMA";
